M48
; DRILL file {KiCad 6.0.2-1.fc35} date Wed 20 Apr 2022 21:26:59 CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-20T21:26:59+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2-1.fc35
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X4.7441Y-3.5039
T2
X4.9213Y-3.5039
T0
M30
